/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef XTKACLMIB_H
#define XTKACLMIB_H

/* function declarations */
void init_xtkaclMIB(void);
Netsnmp_Node_Handler handle_myLogin;
Netsnmp_Node_Handler handle_myCurrentTime;
Netsnmp_Node_Handler handle_myNumGetSet;
Netsnmp_Node_Handler handle_myRAM;

#endif /* XTKACLMIB_H */
